ALTER TABLE clients ADD COLUMN IF NOT EXISTS email VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE clients ADD COLUMN IF NOT EXISTS customer_computex BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS number_contract INTEGER UNIQUE;