CREATE TABLE lots(
    id BIGSERIAL PRIMARY KEY,
    user_id UUID NOT NULL,
    user_cnpj VARCHAR(14) NOT NULL,
    name VARCHAR(100) NOT NULL,
    status VARCHAR(12) NOT NULL CHECK (status IN ('COMPLETED', 'INCOMPLETED', 'DELETED')) DEFAULT 'COMPLETED'
);
